name: qiscus_chat_sdk
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://sdk.qiscus.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # sqflite: ^1.3.0
  sealed_unions: ^3.0.2+2
  json_annotation: ^3.0.1
  meta: ^1.1.8
  dartz: 0.9.0-dev.6
  mqtt_client: ^6.0.0
  retrofit: ^1.3.0
  logger: ^0.8.3
  dio: ^3.0.8
  rxdart: ^0.23.1
  equatable: ^1.1.1
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  json_serializable: ^3.2.5
  retrofit_generator: ^1.3.1+4
  build_runner: ^1.8.0
  mockito: ^4.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
